"""updated turbine model

Revision ID: 43c11b1fe009
Revises: c93ee2e51260
Create Date: 2022-04-21 08:33:03.676513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c11b1fe009'
down_revision = 'c93ee2e51260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('number_of_blades', sa.String(length=20), nullable=True),
    sa.Column('rotor_position', sa.String(length=100), nullable=True),
    sa.Column('wind_direction', sa.String(length=100), nullable=True),
    sa.Column('generator', sa.String(length=100), nullable=True),
    sa.Column('blade_material', sa.String(length=100), nullable=True),
    sa.Column('wind_energy_converted', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('turbines')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbines',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('dimensions', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('weight', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('number_of_blades', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('rotor_position', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('wind_direction', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('generator', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('blade_material', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('wind_energy_converted', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], name='turbines_user_token_fkey'),
    sa.PrimaryKeyConstraint('id', name='turbines_pkey')
    )
    op.drop_table('turbine')
    # ### end Alembic commands ###
