"""added turbine model

Revision ID: c93ee2e51260
Revises: 7f4e1e11698f
Create Date: 2022-04-21 08:01:16.893912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93ee2e51260'
down_revision = '7f4e1e11698f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turbines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dimensions', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('number_of_blades', sa.String(length=20), nullable=True),
    sa.Column('rotor_position', sa.String(length=100), nullable=True),
    sa.Column('wind_direction', sa.String(length=100), nullable=True),
    sa.Column('generator', sa.String(length=100), nullable=True),
    sa.Column('blade_material', sa.String(length=100), nullable=True),
    sa.Column('wind_energy_converted', sa.String(length=100), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_table('turbines')
    # ### end Alembic commands ###
